# Generated by Django 4.1.5 on 2023-05-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0002_rename_hashtags_post_hashtag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hashtag',
            new_name='hashtags',
        ),
    ]
